## Import regression outputs for the 5 specifications, from csv to df

In [1]:
import pandas as pd
import numpy as np
from itertools import product

df = pd.read_csv('../raw_data/output2_clean.csv', sep=',') #output2 is the sample without disability (N=307 055)

df2=df.transpose()
df2.columns = df2.iloc[0]
df2.drop(df2.index[0], inplace=True)
df=df2
df.index=df.index.str.replace('_t:','')
df.index=df.index.str.replace('/:','')
columns_to_convert = ['b1', 'b2', 'b3','b4','b5']  # Specify the columns you want to convert
for column in columns_to_convert:
    df[column] = df[column].astype(float)
df

_t:model,b1,se1,b2,se2,b3,se3,b4,se4,b5,se5,N,N_fail
_cons,0.006520,0.00009,0.004623,0.000069,0.005781,0.000092,0.005257,0.000096,0.004600,0.000093,307055.0,72235.0
gamma,0.115084,0.000673,0.117523,0.000674,0.118200,0.000675,0.118690,0.000675,0.120539,0.000676,NaN,NaN
60.AC,1.146501,0.011945,1.205047,0.012586,1.163559,0.012249,1.163952,0.012262,1.190298,0.012613,NaN,NaN
61.AC,1.077483,0.014162,1.110666,0.014604,1.086397,0.014335,1.082739,0.014289,1.101010,0.014552,NaN,NaN
62.AC,1.071859,0.016001,1.113782,0.016638,1.091194,0.016339,1.092600,0.016358,1.104145,0.016562,NaN,NaN
63.AC,1.046495,0.016953,1.092336,0.017709,1.075804,0.017473,1.079160,0.017525,1.080281,0.017557,NaN,NaN
64.AC,1.085293,0.017948,1.130433,0.018706,1.118516,0.018533,1.129327,0.018714,1.089272,0.018064,NaN,NaN
65b.AC,1.000000,.,1.000000,.,1.000000,.,1.000000,.,1.000000,.,NaN,NaN
1926.coh,1.240706,0.017164,1.194310,0.016522,1.179410,0.016329,1.145954,0.015919,1.201885,0.016721,NaN,NaN
1930.coh,1.135611,0.0146,1.108537,0.014252,1.105171,0.014212,1.087242,0.014004,1.113391,0.01435,NaN,NaN
1935.coh,1.031933,0.013364,1.024934,0.013274,1.027327,0.013306,1.022441,0.013243,1.026395,0.013294,NaN,NaN
1940b.coh,1.000000,.,1.000000,.,1.000000,.,1.000000,.,1.000000,.,NaN,NaN
1945.coh,0.954406,0.015377,0.964071,0.015534,0.962177,0.015503,0.962471,0.015508,0.955253,0.015394,NaN,NaN
1950.coh,0.915315,0.023033,0.928924,0.023379,0.924640,0.023273,0.921920,0.023205,0.856464,0.021592,NaN,NaN
0b.SEX,NaN,NaN,1.000000,.,1.000000,.,1.000000,.,1.000000,.,NaN,NaN
1.SEX,NaN,NaN,1.675294,0.012987,1.769288,0.014065,1.978722,0.017109,1.887753,0.016448,NaN,NaN
0b.imm_d,NaN,NaN,NaN,NaN,1.000000,.,1.000000,.,1.000000,.,NaN,NaN
1.imm_d,NaN,NaN,NaN,NaN,0.760002,0.010962,0.730600,0.010578,0.715829,0.010362,NaN,NaN
0b.mrt,NaN,NaN,NaN,NaN,1.000000,.,1.000000,.,1.000000,.,NaN,NaN
1.mrt,NaN,NaN,NaN,NaN,0.750012,0.006549,0.756651,0.006585,0.816223,0.007218,NaN,NaN
2.mrt,NaN,NaN,NaN,NaN,0.956183,0.027754,1.133791,0.033726,1.025032,0.03064,NaN,NaN
1.p_lvl,NaN,NaN,NaN,NaN,NaN,NaN,1.314221,0.015947,1.041865,0.013417,NaN,NaN
2.p_lvl,NaN,NaN,NaN,NaN,NaN,NaN,1.067798,0.01263,0.948500,0.011447,NaN,NaN
3b.p_lvl,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,.,1.000000,.,NaN,NaN
4.p_lvl,NaN,NaN,NaN,NaN,NaN,NaN,0.924119,0.010659,1.021202,0.012047,NaN,NaN
5.p_lvl,NaN,NaN,NaN,NaN,NaN,NaN,0.882085,0.010841,1.010408,0.012835,NaN,NaN
0.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.604767,0.020964,NaN,NaN
1.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.072123,0.015436,NaN,NaN
2.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.029518,0.014648,NaN,NaN
3b.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,.,NaN,NaN
4.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.965767,0.013501,NaN,NaN
5.pp_lvl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.739030,0.010726,NaN,NaN

### We only want to keep the model with the least variables (model 1)

In [14]:
model_1=pd.DataFrame({'Model1':df['b1']})
model_1 = model_1.dropna()
model_1 #the constant reports the baseline hazard, gamma is the gompertz parameter, other variables report hazard ratios

             Model1
_cons      0.006520
gamma      0.115084
60.AC      1.146501
61.AC      1.077483
62.AC      1.071859
63.AC      1.046495
64.AC      1.085293
65b.AC     1.000000
1926.coh   1.240706
1930.coh   1.135611
1935.coh   1.031933
1940b.coh  1.000000
1945.coh   0.954406
1950.coh   0.915315

### Generate hazard function for each age claim and cohort

In [27]:
def get_hazard(in_df, out_df):
    
    #extract the gamma and constant
    gamma = float(in_df.at['gamma','Model1'])
    cons = float(in_df.at['_cons','Model1'])

    #for each of our variable, 
    #extract the first characters of the index to know what level we are considering
    #extract the hazard ratio
    ac_values = [(index[:2], value) for index, value in in_df.loc[in_df.index.str.endswith('.AC'),'Model1'].items()]
    coh_values = [(index[:4], value) for index, value in in_df.loc[in_df.index.str.endswith('.coh'),'Model1'].items()]


    #define the age range we want to generate the hazard rate on
    t = np.arange(-5,46) #from 60 to 110

    #generate all possible combinations of values
    combinations = product(ac_values, coh_values)
    for ac, coh in combinations:
        #compute hazard rate
        fct = cons * ac[1] * coh[1] * np.exp(t * gamma)
        #store the characteristics used in computing and the hazard rate
        new_row = {'AC': ac[0], 'coh': coh[0],'t': t, 'ht': fct}
        #append stored estimates to the out dataframe
        out_df = out_df.append(new_row, ignore_index=True)
    return out_df

#initialize empty dataframe to receive out_df
hazard = pd.DataFrame(columns=['AC', 'coh', 't', 'ht'])
#run the function
hazard = get_hazard(model_1, hazard)

C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)
C:\Users\Xavier\AppData\Local\Temp\ipykernel_5824\3244871797.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out_df = out_df.append(new_row, ignore_index=True)

In [28]:
hazard

,AC,coh,t,ht
0,60,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.005216451954511294, 0.005852692247297424, 0..."
1,60,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004774588194555781, 0.005356935241423573, 0..."
2,60,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004338682100976946, 0.0048678625466713095, ..."
3,60,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004204422284176343, 0.004717227326455602, 0..."
4,60,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004012725013667151, 0.00450214912028772, 0...."
5,60,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0038483686808297277, 0.004317746571701047, ..."
6,61,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004902427735608336, 0.0055003671175993495, ..."
7,61,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004487163649778366, 0.005034454095316791, 0..."
8,61,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004077498585877329, 0.004574822996556516, 0..."
9,61,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003951321050763304, 0.004433255837885324, 0..."
10,61,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003771163728510592, 0.0042311250845616126, ..."
11,61,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0036167014519188885, 0.004057823350626087, ..."
12,62,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004876839161510126, 0.005471657555899183, 0..."
13,62,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004463742576437669, 0.005008176400140103, 0..."
14,62,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004056215788796563, 0.004550944378951751, 0..."
15,62,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003930696846400457, 0.004410116140245298, 0..."
16,62,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003751479868246305, 0.004209040422923726, 0..."
17,62,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0035978238186146114, 0.0040366432498505555,..."
18,63,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0047614357843004905, 0.0053421786577905455,..."
19,63,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004358114535147943, 0.004889665116274266, 0..."
20,63,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0039602312821897835, 0.00444325283255644, 0..."
21,63,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003837682564846539, 0.004305757091358102, 0..."
22,63,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003662706498448413, 0.004109439541383302, 0..."
23,63,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003512686498001228, 0.0039411218991978955, ..."
24,64,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004937962366423951, 0.005540235836816683, 0..."
25,64,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004519688291099639, 0.005070945702594514, 0..."
26,64,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0041070538215104676, 0.004607983025627143, ..."
27,64,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003979961704403743, 0.004465389735212599, 0..."
28,64,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003798498534460818, 0.004261793862547368, 0..."
29,64,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.00364291665748546, 0.004087235972791253, 0...."
30,65,1926,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004549888708785509, 0.005104829605292472, 0..."
31,65,1930,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.004164486724874885, 0.004672420906238697, 0..."
32,65,1935,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003784281131003764, 0.004245842390605249, 0..."
33,65,1940,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.003667177162668278, 0.004114455483645982, 0..."
34,65,1945,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0034999751536781477, 0.0039268601774335304,..."
35,65,1950,"[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8...","[0.0033566204310591335, 0.0037660207637856807,..."

### Change the previous table which had the hazard rate saved as a list to a dataframe that has the hazard rate saved as a column with all characteristics used in computing

In [29]:
#initialize receiving df
table=pd.DataFrame()
#multiply all characteristics by 51 so that they are lists like the hazard rate
for var in ['AC','coh']:
    hazard[var] = hazard[var].apply(lambda x: [x] * 51)
    table[var]=hazard[var].explode()
#explode all series into a long form dataframe    
table['t'] = hazard['t'].explode()
table['ht'] = hazard['ht'].explode()
table=table.reset_index()
#column identity serves to indicate separate combinations of characteristics used in computing hazard rate
table=table.rename(columns={'index':'identity'})
table.head(60)

    identity  AC   coh   t        ht
0          0  60  1926  -5  0.005216
1          0  60  1926  -4  0.005853
2          0  60  1926  -3  0.006567
3          0  60  1926  -2  0.007367
4          0  60  1926  -1  0.008266
5          0  60  1926   0  0.009274
6          0  60  1926   1  0.010405
7          0  60  1926   2  0.011675
8          0  60  1926   3  0.013098
9          0  60  1926   4  0.014696
10         0  60  1926   5  0.016488
11         0  60  1926   6    0.0185
12         0  60  1926   7  0.020756
13         0  60  1926   8  0.023287
14         0  60  1926   9  0.026128
15         0  60  1926  10  0.029314
16         0  60  1926  11   0.03289
17         0  60  1926  12  0.036901
18         0  60  1926  13  0.041402
19         0  60  1926  14  0.046452
20         0  60  1926  15  0.052118
21         0  60  1926  16  0.058474
22         0  60  1926  17  0.065606
23         0  60  1926  18  0.073608
24         0  60  1926  19  0.082586
25         0  60  1926  20  0.092659
26         0  60  1926  21   0.10396
27         0  60  1926  22   0.11664
28         0  60  1926  23  0.130867
29         0  60  1926  24  0.146828
30         0  60  1926  25  0.164736
31         0  60  1926  26  0.184829
32         0  60  1926  27  0.207372
33         0  60  1926  28  0.232665
34         0  60  1926  29  0.261043
35         0  60  1926  30  0.292881
36         0  60  1926  31  0.328604
37         0  60  1926  32  0.368683
38         0  60  1926  33   0.41365
39         0  60  1926  34  0.464102
40         0  60  1926  35  0.520708
41         0  60  1926  36  0.584218
42         0  60  1926  37  0.655474
43         0  60  1926  38   0.73542
44         0  60  1926  39  0.825118
45         0  60  1926  40  0.925756
46         0  60  1926  41  1.038669
47         0  60  1926  42  1.165353
48         0  60  1926  43  1.307489
49         0  60  1926  44  1.466961
50         0  60  1926  45  1.645883
51         1  60  1930  -5  0.004775
52         1  60  1930  -4  0.005357
53         1  60  1930  -3   0.00601
54         1  60  1930  -2  0.006743
55         1  60  1930  -1  0.007566
56         1  60  1930   0  0.008489
57         1  60  1930   1  0.009524
58         1  60  1930   2  0.010686
59         1  60  1930   3  0.011989

In [33]:
def get_survivor(df):
    
    #gen empty column
    St=None
    #loop over rows to compute survival function
    for index, row in df.iterrows():
        t=row['t']
        prop_surv=1-(row['ht'])
        if t==-5:
            St=prop_surv
        else:
            St*=prop_surv
        df.at[index,'St']=St
    return df

table = get_survivor(table)

In [34]:
table

      identity  AC   coh   t        ht            St
0            0  60  1926  -5  0.005216  9.947835e-01
1            0  60  1926  -4  0.005853  9.889614e-01
2            0  60  1926  -3  0.006567  9.824673e-01
3            0  60  1926  -2  0.007367  9.752291e-01
4            0  60  1926  -1  0.008266  9.671678e-01
...        ...  ..   ...  ..       ...           ...
1831        35  65  1950  41   0.66835  4.063777e-04
1832        35  65  1950  42  0.749868  1.016482e-04
1833        35  65  1950  43  0.841328  1.612877e-05
1834        35  65  1950  44  0.943943  9.041372e-07
1835        35  65  1950  45  1.059073 -5.341045e-08

[1836 rows x 6 columns]